In [1]:
import pandas as pd

In [7]:
pd.set_option('display.max_columns', None)

In [2]:
df_ts_item = pd.read_csv('TS_ITEM.csv', sep=';', encoding='latin-1')

In [4]:
df_ts_item.head(10)

,ID_SAEB,ID_SERIE,TP_DISCIPLINA,NU_BLOCO,NU_POSICAO,ID_ITEM,NU_DESCRITOR_HABILIDADE,TX_GABARITO,TP_ITEM,TP_ITEM_MODELO,A,B,C,B1,B2,B3
0,2023,2,LP,1,1,131475,H4,D,Resposta Objetiva,M3PL,2.643900,-1.246496,0.173011,NaN,NaN,NaN
1,2023,2,LP,1,1,135800,H3.1,A/B,Resposta Construída,MRG,2.359278,NaN,NaN,-1.494441,-1.046531,-0.297927
2,2023,2,LP,1,1,143333,H10,A/B,Produção Textual,MRG,2.518184,NaN,NaN,-0.801163,0.091258,1.345141
3,2023,2,LP,1,2,117433,H2.2,C,Resposta Objetiva,M3PL,2.168779,-1.874237,0.130002,NaN,NaN,NaN
4,2023,2,LP,1,3,132263,H7,D,Resposta Objetiva,M3PL,3.053305,-0.203897,0.214700,NaN,NaN,NaN
5,2023,2,LP,1,4,133034,H9,A,Resposta Objetiva,M3PL,1.449956,-0.671753,0.191736,NaN,NaN,NaN
6,2023,2,LP,1,5,117324,H5,D,Resposta Objetiva,M3PL,2.096955,-0.741969,0.209753,NaN,NaN,NaN
7,2023,2,LP,1,6,132405,H6,B,Resposta Objetiva,M3PL,2.458949,0.277707,0.320032,NaN,NaN,NaN
8,2023,2,LP,1,7,132042,H5,A,Resposta Objetiva,M3PL,1.579026,-0.255899,0.236938,NaN,NaN,NaN
9,2023,2,LP,1,8,117538,H8.1,C,Resposta Objetiva,M3PL,1.671794,0.937818,0.189419,NaN,NaN,NaN

In [ ]:
COLUNAS_SAEB_59ef = [
    'ID_ALUNO', 'ID_REGIAO', 'ID_UF', 'ID_MUNICIPIO', 'ID_ESCOLA',
    'IN_PUBLICA', 'ID_LOCALIZACAO', 'ID_SERIE',
    'PROFICIENCIA_LP_SAEB', 'PROFICIENCIA_MT_SAEB', 
    'PROFICIENCIA_CH_SAEB','PROFICIENCIA_CN_SAEB', 'INSE_ALUNO'
]

COLUNAS_SAEB_34em = [
    'ID_ALUNO', 'ID_REGIAO', 'ID_UF', 'ID_MUNICIPIO', 'ID_ESCOLA',
    'IN_PUBLICA', 'ID_LOCALIZACAO', 'ID_SERIE',
    'PROFICIENCIA_LP_SAEB', 'PROFICIENCIA_MT_SAEB','IN_PROFICIENCIA_LP', 'INSE_ALUNO'
]

In [24]:
df_34EM = pd.read_csv('TS_ALUNO_34EM.csv', sep=';', encoding='latin-1', usecols=COLUNAS_SAEB_34em)

In [25]:
df_34EM

,ID_REGIAO,ID_UF,ID_MUNICIPIO,ID_ESCOLA,IN_PUBLICA,ID_LOCALIZACAO,ID_SERIE,ID_ALUNO,IN_PROFICIENCIA_LP,PROFICIENCIA_LP_SAEB,PROFICIENCIA_MT_SAEB,INSE_ALUNO
0,1,11,6322170,61412274,1,1,12,49408512,1,185.060988,294.357533,4.36
1,1,11,6322170,61412274,1,1,12,49408513,1,216.146812,215.432200,3.43
2,1,11,6322170,61412274,1,1,12,49408514,1,186.287256,190.295017,5.60
3,1,11,6322170,61412274,1,1,12,49408515,1,209.637696,192.578163,5.23
4,1,11,6322170,61412274,1,1,12,49408516,1,215.080370,275.353639,4.83
...,...,...,...,...,...,...,...,...,...,...,...,...
2091332,5,53,6327738,61470349,1,1,12,56415853,1,282.685545,253.131464,2.61
2091333,5,53,6327738,61470349,1,1,12,56415854,0,NaN,NaN,NaN
2091334,5,53,6327738,61470349,1,1,12,56415855,0,NaN,NaN,NaN
2091335,5,53,6327738,61470349,1,1,12,56415856,0,NaN,NaN,NaN
2091336,5,53,6327738,61470349,1,1,12,56415857,0,NaN,NaN,NaN

In [22]:
df_0 = df_34EM[df_34EM['IN_PROFICIENCIA_LP'] == 0]
len(df_0)

565380

In [26]:
df_34EM.isnull().sum()

ID_REGIAO                    0
ID_UF                        0
ID_MUNICIPIO                 0
ID_ESCOLA                    0
IN_PUBLICA                   0
ID_LOCALIZACAO               0
ID_SERIE                     0
ID_ALUNO                     0
IN_PROFICIENCIA_LP           0
PROFICIENCIA_LP_SAEB    565380
PROFICIENCIA_MT_SAEB    565380
INSE_ALUNO              654785
dtype: int64

In [27]:
df_34EM = df_34EM[~df_34EM['PROFICIENCIA_LP_SAEB'].isna()]
df_34EM

,ID_REGIAO,ID_UF,ID_MUNICIPIO,ID_ESCOLA,IN_PUBLICA,ID_LOCALIZACAO,ID_SERIE,ID_ALUNO,IN_PROFICIENCIA_LP,PROFICIENCIA_LP_SAEB,PROFICIENCIA_MT_SAEB,INSE_ALUNO
0,1,11,6322170,61412274,1,1,12,49408512,1,185.060988,294.357533,4.36
1,1,11,6322170,61412274,1,1,12,49408513,1,216.146812,215.432200,3.43
2,1,11,6322170,61412274,1,1,12,49408514,1,186.287256,190.295017,5.60
3,1,11,6322170,61412274,1,1,12,49408515,1,209.637696,192.578163,5.23
4,1,11,6322170,61412274,1,1,12,49408516,1,215.080370,275.353639,4.83
...,...,...,...,...,...,...,...,...,...,...,...,...
2091328,5,53,6327738,61470349,1,1,12,56415849,1,275.823557,306.081284,4.11
2091329,5,53,6327738,61470349,1,1,12,56415850,1,350.815540,306.859976,NaN
2091330,5,53,6327738,61470349,1,1,12,56415851,1,368.480621,333.238472,5.49
2091331,5,53,6327738,61470349,1,1,12,56415852,1,273.603955,258.002648,NaN
2091332,5,53,6327738,61470349,1,1,12,56415853,1,282.685545,253.131464,2.61